name: Maven Build and Docker Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: java-maven
      DOCKERHUB_USERNAME: theyounglord18
      CONTAINER_NAME: maven-jenkins
      PORT_HOST: 9000
      PORT_CONTAINER: 8080

    steps:
      - name: Clean workspace (if needed)
        run: |
          echo "Workspace cleanup handled by GitHub Actions runners"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.8.9' # match 'maven3' in Jenkins

      - name: Build WAR with Maven
        run: mvn clean package

      - name: Docker Clean Previous Container/Image (optional)
        run: |
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
          docker rmi $IMAGE_NAME || true
          docker rmi $DOCKERHUB_USERNAME/$IMAGE_NAME:latest || true

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

      - name: Run Docker Container
        run: |
          docker run -d -p $PORT_HOST:$PORT_CONTAINER --name $CONTAINER_NAME $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
